# Generated by Django 5.0.14 on 2025-12-02 22:33

import apps.applications.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('reminder_days_before', models.JSONField(default=list, help_text='Days before deadline to send reminders (e.g., [7, 3, 1])')),
                ('auto_escalate', models.BooleanField(default=False, help_text='Automatically escalate state on deadline')),
                ('escalation_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_TRIAGE', 'In Triage'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('DECISION_PENDING', 'Decision Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('UNDER_REVISION', 'Under Revision'), ('APPEAL_PENDING', 'Appeal Pending'), ('APPEAL_REVIEWED', 'Appeal Reviewed'), ('ARCHIVED', 'Archived')], help_text='Status to transition to on deadline', max_length=30)),
                ('applies_to_statuses', models.JSONField(default=list, help_text='List of statuses this rule applies to')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Application title', max_length=500)),
                ('call_program', models.CharField(db_index=True, help_text='Grant call or program name', max_length=255)),
                ('abstract', models.TextField(help_text='Brief abstract or summary')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Requested funding amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_TRIAGE', 'In Triage'), ('ASSIGNED', 'Assigned'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('DECISION_PENDING', 'Decision Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('UNDER_REVISION', 'Under Revision'), ('APPEAL_PENDING', 'Appeal Pending'), ('APPEAL_REVIEWED', 'Appeal Reviewed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Current application status', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Application deadline', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorization and matching (e.g., ['biology', 'climate'])")),
                ('applicant', models.ForeignKey(help_text='User who submitted the application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Version number (incremental)', validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.JSONField(help_text='Complete application data snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='applications.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('STATE_CHANGE', 'State Change'), ('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DELETED', 'Document Deleted'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_SUBMITTED', 'Review Submitted'), ('COMMENT_ADDED', 'Comment Added'), ('DECISION_MADE', 'Decision Made'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('details', models.JSONField(default=dict, help_text='Detailed information about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.application')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PROPOSAL', 'Proposal Document'), ('BUDGET', 'Budget Document'), ('CV', 'Curriculum Vitae'), ('LETTER', 'Letter of Support'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to=apps.applications.models.document_upload_path)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='application_status_413525_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['deadline'], name='application_deadlin_337ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationversion',
            index=models.Index(fields=['application', '-version_number'], name='application_applica_da12b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationversion',
            unique_together={('application', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='application_action__b6facf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['application', '-timestamp'], name='application_applica_7e0dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-timestamp'], name='application_actor_i_1eb3fd_idx'),
        ),
    ]
