# Generated by Django 5.0.14 on 2025-12-03 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for appeal')),
                ('supporting_documents', models.TextField(blank=True, help_text='References to supporting documents')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, help_text='Admin decision on appeal')),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_appeals', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='applications.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Call title', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of the funding opportunity')),
                ('deadline', models.DateTimeField(db_index=True, help_text='Application submission deadline')),
                ('is_open', models.BooleanField(default=True, help_text='Whether this call is currently accepting applications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_amount_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum funding amount', max_digits=12, null=True)),
                ('funding_amount_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum funding amount', max_digits=12, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Who can apply')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='call',
            field=models.ForeignKey(blank=True, help_text='The call this application is responding to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.call'),
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changes_required', models.TextField(help_text='Specific changes that need to be made')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Revision'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_notes', models.TextField(blank=True, help_text="Applicant's notes on revisions made")),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='applications.application')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['is_open', '-deadline'], name='application_is_open_9cc231_idx'),
        ),
    ]
