# Generated by Django 5.0.14 on 2025-12-02 22:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rubric name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Rubric description and instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rubric is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], db_index=True, default='ASSIGNED', max_length=20)),
                ('is_blinded', models.BooleanField(default=True, help_text='Whether reviewer sees blinded application (PI/team hidden)')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Review due date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this assignment')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='applications.application')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'REVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reviews.rubric')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scores', models.JSONField(default=dict, help_text='Dictionary mapping criterion IDs to scores')),
                ('overall_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Weighted overall score (0-100)', max_digits=5, null=True)),
                ('strengths', models.TextField(blank=True, help_text='Application strengths')),
                ('weaknesses', models.TextField(blank=True, help_text='Application weaknesses')),
                ('recommendation', models.TextField(blank=True, help_text='Overall recommendation')),
                ('confidential_comments', models.TextField(blank=True, help_text='Comments visible only to admins (not shared with applicant)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewassignment')),
            ],
            options={
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Criterion name', max_length=255)),
                ('description', models.TextField(help_text='Detailed description and scoring guidelines')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of this criterion in overall score', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_score', models.IntegerField(default=0, help_text='Minimum possible score', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.IntegerField(default=10, help_text='Maximum possible score', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=True, help_text='Whether this criterion must be scored')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='reviews.rubric')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='COIFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coi_type', models.CharField(choices=[('FINANCIAL', 'Financial Conflict'), ('PERSONAL', 'Personal Relationship'), ('PROFESSIONAL', 'Professional Relationship'), ('INSTITUTIONAL', 'Institutional Conflict'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of the conflict of interest')),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether admin has addressed this COI')),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on how COI was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_flags', to='applications.application')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cois', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-declared_at'],
                'unique_together': {('reviewer', 'application')},
            },
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['reviewer', 'status'], name='reviews_rev_reviewe_73b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewassignment',
            index=models.Index(fields=['application', 'status'], name='reviews_rev_applica_744d49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('application', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('rubric', 'name')},
        ),
    ]
