# Generated by Django 5.0.14 on 2025-12-03 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_appeal_call_application_call_revisionrequest_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Session name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description and objectives')),
                ('consensus_score', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed-upon consensus score', max_digits=5, null=True)),
                ('consensus_scores_detail', models.JSONField(blank=True, default=dict, help_text='Consensus scores per criterion {criterion_id: score}')),
                ('session_date', models.DateTimeField(help_text='When the calibration session takes place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the session has been completed')),
                ('discussion_notes', models.TextField(blank=True, help_text='Notes from the calibration discussion')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calibrations', to=settings.AUTH_USER_MODEL)),
                ('example_application', models.ForeignKey(help_text='Example application for scoring practice', on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to='applications.application')),
                ('participants', models.ManyToManyField(help_text='Reviewers participating in this session', limit_choices_to={'role': 'REVIEWER'}, related_name='calibration_sessions', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions', to='reviews.rubric')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, help_text="Reviewer's scores {criterion_id: score}")),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, help_text="Reviewer's comments on their scoring")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_scores', to='reviews.calibrationsession')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'reviewer')},
            },
        ),
    ]
