# Generated by Django 5.0.14 on 2025-12-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=255, unique=True)),
                ('template_type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('REVIEW_REMINDER', 'Review Reminder'), ('REVIEW_OVERDUE', 'Review Overdue'), ('DECISION_APPROVED', 'Decision - Approved'), ('DECISION_REJECTED', 'Decision - Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('COI_DECLARED', 'COI Declared'), ('CUSTOM', 'Custom')], db_index=True, max_length=50)),
                ('subject', models.CharField(help_text='Email subject line (supports template variables)', max_length=255)),
                ('body', models.TextField(help_text='Email body (supports template variables like {{applicant_name}}, {{application_title}}, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('REMINDER', 'Reminder')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
